PATH_TO_PRETRAINED_MODELS = "./PretrainedModels/"
PATH_TO_SAVED_MODELS = "./ckpt/"
PATH_TO_PERFORMACE = "./PerformanceLog/"
PATH_TO_CKPT = "./ckpt/"

[MSP-PODCAST]
PATH_TO_LABEL = '/workspace/MSP-PODCAST/Labels/processed_labels.csv'
PATH_TO_LABEL_SOFT_P = '/workspace/MSP-PODCAST/Labels/processed_labels_soft_P.csv'
PATH_TO_LABEL_SOFT_S = '/workspace/MSP-PODCAST/Labels/processed_labels_soft_S.csv'
PATH_TO_AUDIO = '/workspace/MSP-PODCAST/Audios'
PATH_TO_TRANSCRIPT = '/datas/store162/othsueh/MSP-Podcast/Transcripts'
PATH_TO_DATASET = '/datas/store162/othsueh/wds_6_test/MSP-Podcast'

[BIIC-PODCAST]
PATH_TO_LABEL = '/workspace/BIIC-PODCAST/Labels/processed_labels.csv'
PATH_TO_LABEL_SOFT_S = '/workspace/BIIC-PODCAST/Labels/processed_labels_soft_S.csv'
PATH_TO_AUDIO = '/workspace/BIIC-PODCAST/Audios'
