PATH_TO_PRETRAINED_MODELS = "./PretrainedModels/"
PATH_TO_SAVED_MODELS = "./ckpt/"
PATH_TO_PERFORMACE = "./PerformanceLog/"
PATH_TO_CKPT = "./ckpt/"

[MSPPODCAST]
PATH_TO_LABEL = '/datas/store163/othsueh/Emo_analyze/6emo/test/msp_podcast_6emo.csv'
PATH_TO_AUDIO = '/datas/store162/othsueh/MSP-Podcast/Audios'
PATH_TO_TRANSCRIPT = '/datas/store162/othsueh/MSP-Podcast/Transcripts'
PATH_TO_DATASET = '/datas/store162/othsueh/wds_6_test/MSP-Podcast'
